FC      = gfortran
FFLAGS  = -Wall -O2 -std=f2008 -fPIC
LDFLAGS = -shared

SRC = DSP/numtype.f90 

OBJDIR = build
OBJ = $(patsubst DSP/%.f90,$(OBJDIR)/%.o,$(SRC))

TARGET = VOID_Verb.so

all: $(TARGET)

$(TARGET): $(OBJ)
	$(FC) $(OBJ) -o $@ $(LDFLAGS)

$(OBJDIR)/%.o: DSP/%.f90 | $(OBJDIR)
	$(FC) $(FFLAGS) -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	rm -rf $(OBJDIR) $(TARGET)
