name: Target Repo Unit Tests

on:
  push:
    paths:
      - 'kernel/**' 
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and run tests
        run: |
          python3 lib.py
          mkdir -p build
          cd build
          cmake ..
          make 
          cd ..
          build/UnitTestExe
